export const API_CODES = {
  // Auth related codes
  AUTH: {
    SUCCESS: 'AUTH_SUCCESS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    TOKEN_EXPIRED: 'TOKEN_EXPIRED',
    TOKEN_INVALID: 'TOKEN_INVALID',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
  },

  // Validation codes
  VALIDATION: {
    INVALID_DATA: 'INVALID_DATA',
    REQUIRED_FIELD: 'REQUIRED_FIELD',
    INVALID_FORMAT: 'INVALID_FORMAT',
    PASSWORD_TOO_WEAK: 'PASSWORD_TOO_WEAK',
  },

  // Common operation codes
  OPERATION: {
    SUCCESS: 'OPERATION_SUCCESS',
    FAILED: 'OPERATION_FAILED',
    NOT_FOUND: 'NOT_FOUND',
    FORBIDDEN: 'FORBIDDEN',
    UNAUTHORIZED: 'UNAUTHORIZED',
  },

  // Data related codes
  DATA: {
    NOT_FOUND: 'DATA_NOT_FOUND',
    ALREADY_EXISTS: 'DATA_EXISTS',
    INVALID_STATE: 'INVALID_STATE',
  },
}
