/**
 * API Response Codes
 */
export const API_RESPONSE_CODES = {
  // Success codes
  SUCCESS: {
    LOGIN: 'LOGIN_SUCCESS',
    REGISTRATION: 'REGISTRATION_SUCCESS',
    USER_DATA: 'USER_DATA_SUCCESS',
    PASSWORD_RESET: 'PASSWORD_RESET_SUCCESS',
    EMAIL_VERIFICATION: 'EMAIL_VERIFICATION_SUCCESS',
    // New user management success codes
    USERS_LIST: 'USERS_LIST_SUCCESS',
    USER_UPDATE: 'USER_UPDATE_SUCCESS',
    USER_DELETE: 'USER_DELETE_SUCCESS',
    USERS_SEARCH: 'USERS_SEARCH_SUCCESS',
  },

  // Authentication error codes
  AUTH_ERROR: {
    MISSING_CREDENTIALS: 'MISSING_CREDENTIALS',
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    LOGIN_FAILED: 'LOGIN_FAILED',
    ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
    EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
    ACCOUNT_BLOCKED: 'ACCOUNT_BLOCKED',
    EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
    // New JWT related errors
    JWT_CONFIG_MISSING: 'JWT_CONFIG_MISSING',
  },

  // Token error codes
  TOKEN_ERROR: {
    NOT_PROVIDED: 'TOKEN_NOT_PROVIDED',
    INVALID: 'INVALID_TOKEN',
    EXPIRED: 'TOKEN_EXPIRED',
  },

  // User error codes
  USER_ERROR: {
    NOT_FOUND: 'USER_NOT_FOUND',
    INVALID_ROLE: 'INVALID_ROLE',
    EMAIL_EXISTS: 'EMAIL_ALREADY_EXISTS',
    INVALID_DATA: 'INVALID_USER_DATA',
  },

  // System error codes
  SYSTEM_ERROR: {
    GENERAL: 'SYSTEM_ERROR',
    DATABASE: 'DATABASE_ERROR',
    EMAIL_SEND: 'EMAIL_SEND_ERROR',
  },
}
